name: Envoyer un message à Discord

on:
  push:
  workflow_dispatch:

jobs:
  send-discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit
        id: get_commit_message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Send notification
        run: |
          curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -d '{
            "username": "Github BOT de Springfield",
            "avatar_url": "https://imgur.com/gallery/id-stay-away-from-springfield-if-i-were-you-5XbKwJU",
            "embeds": [
              {
                "title": "Nouveau commit",
                "description": "${{ env.message }}",
                "color": 8388736,
                "fields": [
                    {
                        "name": "Repository",
                        "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})"
                    },
                    {
                        "name": "Branch",
                        "value": "${{ github.ref }}"
                    }
                ],
                "footer": {
                  "text": "Github Actions - Automatisation"
                }
              }
            ]
          }'