name: Envoyer un message à Discord

on:
  push:
  workflow_dispatch:

jobs:
  send-discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit
        id: get_commit_message
        run: |
          # Récupérer et échapper le message du commit
          commit_msg=$(git log -1 --pretty=%B)
          commit_msg="${commit_msg//'%'/'%25'}"
          commit_msg="${commit_msg//$'\n'/'%0A'}"
          commit_msg="${commit_msg//$'\r'/'%0D'}"
          commit_msg="${commit_msg//'"'/'\"'}"
          echo "message=$commit_msg" >> $GITHUB_ENV

      - name: Send notification
        run: |
          # Préparer le message pour le JSON
          message=$(echo "${{ env.message }}" | sed 's/%0A/\\n/g' | sed 's/%0D/\\r/g' | sed 's/%25/%/g')
          
          curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -d '{
            "username": "BOT de Springfield",
            "embeds": [
              {
                "title": "Nouveau commit",
                "description": "'"${message}"'",
                "color": 8388736,
                "fields": [
                    {
                        "name": "Repository",
                        "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})"
                    },
                    {
                        "name": "Branch",
                        "value": "${{ github.ref }}"
                    }
                ],
                "footer": {
                  "text": "Github Actions - Automatisation"
                }
              }
            ]
          }'