name: Ajout d'un commentaire automatique sur les PR

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    add-comment:
        runs-on: ubuntu-latest
        steps:
            - name: Cloner le dépot Github
              uses: actions/checkout@v4

            - name: Récupérer le message du dernier commit
              id: get_commit_message
              run: |
                commit_msg=$(git log -1 --pretty=%B)
                echo "message=$commit_msg" >> $GITHUB_ENV
            
            - name: Ajouter un commentaire sur la PR
              uses: actions/github-script@v6
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                  github.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: "Le dernier commit ajouté à la branche est : ${{ env.message }}"
                  })
