name : Mon deuxième workflow

on :
  push :
    branches :
      - main
      
  workflow_dispatch:
    inputs:
      raison:
        description: 'Raison du lancement manuel'
        required: true
        type: string
      environnement:
        description: 'ubuntu-latest ou ubuntu-22.04'
        required: false
        type: choice
        options:
          - dev
          - staging
          - prod
        default: 'dev'
    

jobs :
  afficher-message :
    runs-on: ubuntu-latest
    steps :
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Récupérer le nom du dernier commit
        run: echo "nom=$(git log -1 --pretty=%B)"
