name : Mon deuxième workflow

on :
  push :
    branches :
      - main

jobs :
  afficher-message :
    runs-on: ubuntu-latest
    steps :
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Récupérer le nom du dernier commit
        run: echo "nom=$(git log -1 --pretty=%B)"
