name: Utilisation des Github Secrets

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    secure-api-call:
        runs-on: ubuntu-latest
        steps:
            - name: Cloner le dépot Github
              uses: actions/checkout@v4

            - name: Afficher le secret
              run: |
                echo "Ma clé API sécurisée est ${{secrets.API_KEY}}"
